name: freeobmin
description: A modern Flutter app for exchanging items without money
publish_to: 'none'
version: 1.5.0+7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # ? ОБНОВЛЕНО для совместимости с Android SDK 36
  # Основные для работы приложения
  shared_preferences: ^2.2.3  # Обновлено
  google_fonts: ^6.1.0
  
  # Для изображений и галереи
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  image_picker: ^1.0.6  # ? Обновлено для Android 36
  share_plus: ^10.0.2
  app_links: ^6.3.2
  url_launcher: ^6.2.6
  package_info_plus: ^4.0.0
  http: ^1.0.0

  firebase_core: ^3.4.1
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.3.1
  flutter_local_notifications: ^17.2.3  # ? Вернули новую версию
  dotted_border: ^2.1.0
  firebase_messaging: 15.2.10
  onesignal_flutter: ^5.1.2
  flutter_dotenv: ^5.1.0

    # Дополнительные пакеты
  pull_to_refresh: ^2.0.0
  # Для UI эффектов
  shimmer: ^3.0.0
  badges: ^3.0.3  # Обновлено
  flutter_animate: ^4.1.1
  
  # ? ДОБАВИТЬ ЭТИ ПЛАГИНЫ (обязательно!)
  path_provider: ^2.1.3  # Добавить
  sqflite: ^2.3.2  # Добавить
  android_intent_plus: ^6.0.0
  dio: ^5.4.3
  open_filex: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - lib/locations.json
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logo_launcher.png
  adaptive_icon_background: "#111827"
  adaptive_icon_foreground: assets/images/logo_launcher.png

  
